---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-secrets-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: vault-secrets-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  config:
    # nodeSelector:
    #   node-role.kubernetes.io/infra: ''
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
