---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: cert-manager
  name: cert-manager
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: cert-manager
    repoURL: https://github.com/alvarolop/ocp-secure-integration.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
