---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hashicorp-vault
  name: hashicorp-vault
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.29.1
    helm:
      # Most of the following config comes from the Secret CSI Store Driver
      values: |
        global:
          openshift: true
          enabled: false
          namespace: vault
        csi:
          enabled: true
          image:
            repository: docker.io/hashicorp/vault-csi-provider
          agent:
            image:
              repository: docker.io/hashicorp/vault
          daemonSet:
            providersDir: /var/run/secrets-store-csi-providers

    chart: vault
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
