---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hashicorp-vault
  name: hashicorp-vault
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hashicorp-vault
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.29.1
    helm:
      values: |
        global:
          openshift: true
        server:
          dev:
            enabled: true
          route:
            enabled: true
            host: ''
            tls: 
              termination: edge
    chart: vault
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
