---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.29.1
  valuesFile: values.yaml
  releaseName: vault

resources:
  - deployment-test-sidecar-agent-injector.yaml
