---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-secrets-store-csi-driver
  namespace: test-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-secrets-store-csi-driver
  template:
    metadata:
      labels:
        app: test-secrets-store-csi-driver
    spec:
      containers:
        - name: test
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          command:
            - "/bin/bash"
            - "-c"
            - "while true; do cat /mnt/secrets-store/*; echo ''; sleep 10; done"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "my-vault-provider"  
      terminationGracePeriodSeconds: 0