---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-secrets-store-csi-driver-from-secret
  namespace: test-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-secrets-store-csi-driver-from-secret
  template:
    metadata:
      labels:
        app: test-secrets-store-csi-driver-from-secret
    spec:
      containers:
        - name: test
          image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
          env:
          - name: SECRET_VALUE
            valueFrom:
              secretKeyRef:
                name: vault-synced-secret
                key: key1
          command:
            - "/bin/bash"
            - "-c"
            - "while true; do echo $SECRET_VALUE; sleep 10; done"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vault-to-secret"
      terminationGracePeriodSeconds: 0