---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cluster-csi-drivers
  namespace: openshift-cluster-csi-drivers
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  upgradeStrategy: Default
