---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns-cert-manager-operator.yaml
  - ns-cert-manager.yaml

  - credentialsrequest-cert-manager.yaml

  - og-openshift-cert-manager-operator.yaml
  - sub-openshift-cert-manager-operator.yaml

  - certmanager-cluster.yaml

  - cert-manager-monitoring
