---
{{- $clusterDomainFromValues := .Values.clusterDomain | default "" -}}
{{- if eq $clusterDomainFromValues "" -}}
  {{- $dnsConfig := lookup "config.openshift.io/v1" "DNS" "cluster" "" -}}
  {{- $clusterDomain := $dnsConfig.spec.baseDomain | default "default.cluster.local" -}}
{{- else -}}
  {{- $clusterDomain := $clusterDomainFromValues -}}
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocp-api
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "10"
spec:
  commonName: "api.{{ .Values.clusterDomain }}" 
  dnsNames:
  - "api.{{ .Values.clusterDomain }}" 
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: api-certs
